/* 
 * Wirk
 *
 * <p>API for api.wirk.io</p> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@wirk.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Io.Wirk.Api.Wirk.Client;
using Io.Wirk.Api.Wirk.Model;

namespace Io.Wirk.Api.Wirk.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAppProjectApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>AppProjectReaderServiceModel</returns>
        AppProjectReaderServiceModel Get (int? id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>ApiResponse of AppProjectReaderServiceModel</returns>
        ApiResponse<AppProjectReaderServiceModel> GetWithHttpInfo (int? id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Post app project
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>AppProjectReaderServiceModel</returns>
        AppProjectReaderServiceModel Post (AppProjectWriterServiceModel appProjectWriterServiceModel);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Post app project
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>ApiResponse of AppProjectReaderServiceModel</returns>
        ApiResponse<AppProjectReaderServiceModel> PostWithHttpInfo (AppProjectWriterServiceModel appProjectWriterServiceModel);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>Task of AppProjectReaderServiceModel</returns>
        System.Threading.Tasks.Task<AppProjectReaderServiceModel> GetAsync (int? id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>Task of ApiResponse (AppProjectReaderServiceModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<AppProjectReaderServiceModel>> GetAsyncWithHttpInfo (int? id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Post app project
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>Task of AppProjectReaderServiceModel</returns>
        System.Threading.Tasks.Task<AppProjectReaderServiceModel> PostAsync (AppProjectWriterServiceModel appProjectWriterServiceModel);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Post app project
        /// </remarks>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>Task of ApiResponse (AppProjectReaderServiceModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<AppProjectReaderServiceModel>> PostAsyncWithHttpInfo (AppProjectWriterServiceModel appProjectWriterServiceModel);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AppProjectApi : IAppProjectApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppProjectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AppProjectApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AppProjectApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AppProjectApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Get
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>AppProjectReaderServiceModel</returns>
        public AppProjectReaderServiceModel Get (int? id)
        {
             ApiResponse<AppProjectReaderServiceModel> localVarResponse = GetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Get
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>ApiResponse of AppProjectReaderServiceModel</returns>
        public ApiResponse< AppProjectReaderServiceModel > GetWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AppProjectApi->Get");

            var localVarPath = "/AppProject/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (Authorization) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (localVarStatusCode >= 400)
                throw new ApiException (localVarStatusCode, "Error calling Get: " + localVarResponse.Content, localVarResponse.Content);
            else if (localVarStatusCode == 0)
                throw new ApiException (localVarStatusCode, "Error calling Get: " + localVarResponse.ErrorMessage, localVarResponse.ErrorMessage);

            return new ApiResponse<AppProjectReaderServiceModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AppProjectReaderServiceModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AppProjectReaderServiceModel)));
            
        }

        /// <summary>
        ///  Get
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>Task of AppProjectReaderServiceModel</returns>
        public async System.Threading.Tasks.Task<AppProjectReaderServiceModel> GetAsync (int? id)
        {
             ApiResponse<AppProjectReaderServiceModel> localVarResponse = await GetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Get
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">ID</param>
        /// <returns>Task of ApiResponse (AppProjectReaderServiceModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AppProjectReaderServiceModel>> GetAsyncWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AppProjectApi->Get");

            var localVarPath = "/AppProject/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (Authorization) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (localVarStatusCode >= 400)
                throw new ApiException (localVarStatusCode, "Error calling Get: " + localVarResponse.Content, localVarResponse.Content);
            else if (localVarStatusCode == 0)
                throw new ApiException (localVarStatusCode, "Error calling Get: " + localVarResponse.ErrorMessage, localVarResponse.ErrorMessage);

            return new ApiResponse<AppProjectReaderServiceModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AppProjectReaderServiceModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AppProjectReaderServiceModel)));
            
        }

        /// <summary>
        ///  Post app project
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>AppProjectReaderServiceModel</returns>
        public AppProjectReaderServiceModel Post (AppProjectWriterServiceModel appProjectWriterServiceModel)
        {
             ApiResponse<AppProjectReaderServiceModel> localVarResponse = PostWithHttpInfo(appProjectWriterServiceModel);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Post app project
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>ApiResponse of AppProjectReaderServiceModel</returns>
        public ApiResponse< AppProjectReaderServiceModel > PostWithHttpInfo (AppProjectWriterServiceModel appProjectWriterServiceModel)
        {
            // verify the required parameter 'appProjectWriterServiceModel' is set
            if (appProjectWriterServiceModel == null)
                throw new ApiException(400, "Missing required parameter 'appProjectWriterServiceModel' when calling AppProjectApi->Post");

            var localVarPath = "/AppProject";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (appProjectWriterServiceModel != null && appProjectWriterServiceModel.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(appProjectWriterServiceModel); // http body (model) parameter
            }
            else
            {
                localVarPostBody = appProjectWriterServiceModel; // byte array
            }

            // authentication (Authorization) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (localVarStatusCode >= 400)
                throw new ApiException (localVarStatusCode, "Error calling Post: " + localVarResponse.Content, localVarResponse.Content);
            else if (localVarStatusCode == 0)
                throw new ApiException (localVarStatusCode, "Error calling Post: " + localVarResponse.ErrorMessage, localVarResponse.ErrorMessage);

            return new ApiResponse<AppProjectReaderServiceModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AppProjectReaderServiceModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AppProjectReaderServiceModel)));
            
        }

        /// <summary>
        ///  Post app project
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>Task of AppProjectReaderServiceModel</returns>
        public async System.Threading.Tasks.Task<AppProjectReaderServiceModel> PostAsync (AppProjectWriterServiceModel appProjectWriterServiceModel)
        {
             ApiResponse<AppProjectReaderServiceModel> localVarResponse = await PostAsyncWithHttpInfo(appProjectWriterServiceModel);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Post app project
        /// </summary>
        /// <exception cref="Io.Wirk.Api.Wirk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appProjectWriterServiceModel">Definition of the appProject</param>
        /// <returns>Task of ApiResponse (AppProjectReaderServiceModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AppProjectReaderServiceModel>> PostAsyncWithHttpInfo (AppProjectWriterServiceModel appProjectWriterServiceModel)
        {
            // verify the required parameter 'appProjectWriterServiceModel' is set
            if (appProjectWriterServiceModel == null)
                throw new ApiException(400, "Missing required parameter 'appProjectWriterServiceModel' when calling AppProjectApi->Post");

            var localVarPath = "/AppProject";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (appProjectWriterServiceModel != null && appProjectWriterServiceModel.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(appProjectWriterServiceModel); // http body (model) parameter
            }
            else
            {
                localVarPostBody = appProjectWriterServiceModel; // byte array
            }

            // authentication (Authorization) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (localVarStatusCode >= 400)
                throw new ApiException (localVarStatusCode, "Error calling Post: " + localVarResponse.Content, localVarResponse.Content);
            else if (localVarStatusCode == 0)
                throw new ApiException (localVarStatusCode, "Error calling Post: " + localVarResponse.ErrorMessage, localVarResponse.ErrorMessage);

            return new ApiResponse<AppProjectReaderServiceModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AppProjectReaderServiceModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AppProjectReaderServiceModel)));
            
        }

    }
}
