/* 
 * Wirk
 *
 * API for api.wirk.io
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Io.Wirk.Api.Wirk.Model
{
    /// <summary>
    /// Model for AppProject Get
    /// </summary>
    [DataContract]
    public partial class AppProjectReaderServiceModel :  IEquatable<AppProjectReaderServiceModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppProjectReaderServiceModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppProjectReaderServiceModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppProjectReaderServiceModel" /> class.
        /// </summary>
        /// <param name="AppName">AppName (required).</param>
        /// <param name="AppProjectState">AppProjectState.</param>
        /// <param name="CreationDate">CreationDate.</param>
        /// <param name="Credit">Credit.</param>
        /// <param name="HasInstruction">HasInstruction.</param>
        /// <param name="HasQuestionOptions">HasQuestionOptions.</param>
        /// <param name="IdApp">IdApp.</param>
        /// <param name="IdAppProject">IdAppProject.</param>
        /// <param name="IdQuality">IdQuality.</param>
        /// <param name="Instruction">Instruction.</param>
        /// <param name="NbTaskClosed">NbTaskClosed.</param>
        /// <param name="NbTotalTask">NbTotalTask.</param>
        /// <param name="Qualities">Qualities.</param>
        /// <param name="QualityName">QualityName.</param>
        /// <param name="QuestionOptions">QuestionOptions.</param>
        /// <param name="Title">Title.</param>
        /// <param name="TitleQuestionOptions">TitleQuestionOptions.</param>
        /// <param name="UrlNotification">UrlNotification.</param>
        public AppProjectReaderServiceModel(string AppName = null, int? AppProjectState = null, DateTime? CreationDate = null, int? Credit = null, bool? HasInstruction = null, bool? HasQuestionOptions = null, int? IdApp = null, int? IdAppProject = null, int? IdQuality = null, string Instruction = null, int? NbTaskClosed = null, int? NbTotalTask = null, List<QualityReaderServiceModel> Qualities = null, string QualityName = null, List<string> QuestionOptions = null, string Title = null, string TitleQuestionOptions = null, string UrlNotification = null)
        {
            // to ensure "AppName" is required (not null)
            if (AppName == null)
            {
                throw new InvalidDataException("AppName is a required property for AppProjectReaderServiceModel and cannot be null");
            }
            else
            {
                this.AppName = AppName;
            }
            this.AppProjectState = AppProjectState;
            this.CreationDate = CreationDate;
            this.Credit = Credit;
            this.HasInstruction = HasInstruction;
            this.HasQuestionOptions = HasQuestionOptions;
            this.IdApp = IdApp;
            this.IdAppProject = IdAppProject;
            this.IdQuality = IdQuality;
            this.Instruction = Instruction;
            this.NbTaskClosed = NbTaskClosed;
            this.NbTotalTask = NbTotalTask;
            this.Qualities = Qualities;
            this.QualityName = QualityName;
            this.QuestionOptions = QuestionOptions;
            this.Title = Title;
            this.TitleQuestionOptions = TitleQuestionOptions;
            this.UrlNotification = UrlNotification;
        }
        
        /// <summary>
        /// Gets or Sets AppName
        /// </summary>
        [DataMember(Name="AppName", EmitDefaultValue=false)]
        public string AppName { get; set; }
        /// <summary>
        /// Gets or Sets AppProjectState
        /// </summary>
        [DataMember(Name="AppProjectState", EmitDefaultValue=false)]
        public int? AppProjectState { get; set; }
        /// <summary>
        /// Gets or Sets CreationDate
        /// </summary>
        [DataMember(Name="CreationDate", EmitDefaultValue=false)]
        public DateTime? CreationDate { get; set; }
        /// <summary>
        /// Gets or Sets Credit
        /// </summary>
        [DataMember(Name="Credit", EmitDefaultValue=false)]
        public int? Credit { get; set; }
        /// <summary>
        /// Gets or Sets HasInstruction
        /// </summary>
        [DataMember(Name="HasInstruction", EmitDefaultValue=false)]
        public bool? HasInstruction { get; set; }
        /// <summary>
        /// Gets or Sets HasQuestionOptions
        /// </summary>
        [DataMember(Name="HasQuestionOptions", EmitDefaultValue=false)]
        public bool? HasQuestionOptions { get; set; }
        /// <summary>
        /// Gets or Sets IdApp
        /// </summary>
        [DataMember(Name="IdApp", EmitDefaultValue=false)]
        public int? IdApp { get; set; }
        /// <summary>
        /// Gets or Sets IdAppProject
        /// </summary>
        [DataMember(Name="IdAppProject", EmitDefaultValue=false)]
        public int? IdAppProject { get; set; }
        /// <summary>
        /// Gets or Sets IdQuality
        /// </summary>
        [DataMember(Name="IdQuality", EmitDefaultValue=false)]
        public int? IdQuality { get; set; }
        /// <summary>
        /// Gets or Sets Instruction
        /// </summary>
        [DataMember(Name="Instruction", EmitDefaultValue=false)]
        public string Instruction { get; set; }
        /// <summary>
        /// Gets or Sets NbTaskClosed
        /// </summary>
        [DataMember(Name="NbTaskClosed", EmitDefaultValue=false)]
        public int? NbTaskClosed { get; set; }
        /// <summary>
        /// Gets or Sets NbTotalTask
        /// </summary>
        [DataMember(Name="NbTotalTask", EmitDefaultValue=false)]
        public int? NbTotalTask { get; set; }
        /// <summary>
        /// Gets or Sets Qualities
        /// </summary>
        [DataMember(Name="Qualities", EmitDefaultValue=false)]
        public List<QualityReaderServiceModel> Qualities { get; set; }
        /// <summary>
        /// Gets or Sets QualityName
        /// </summary>
        [DataMember(Name="QualityName", EmitDefaultValue=false)]
        public string QualityName { get; set; }
        /// <summary>
        /// Gets or Sets QuestionOptions
        /// </summary>
        [DataMember(Name="QuestionOptions", EmitDefaultValue=false)]
        public List<string> QuestionOptions { get; set; }
        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="Title", EmitDefaultValue=false)]
        public string Title { get; set; }
        /// <summary>
        /// Gets or Sets TitleQuestionOptions
        /// </summary>
        [DataMember(Name="TitleQuestionOptions", EmitDefaultValue=false)]
        public string TitleQuestionOptions { get; set; }
        /// <summary>
        /// Gets or Sets UrlNotification
        /// </summary>
        [DataMember(Name="UrlNotification", EmitDefaultValue=false)]
        public string UrlNotification { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AppProjectReaderServiceModel {\n");
            sb.Append("  AppName: ").Append(AppName).Append("\n");
            sb.Append("  AppProjectState: ").Append(AppProjectState).Append("\n");
            sb.Append("  CreationDate: ").Append(CreationDate).Append("\n");
            sb.Append("  Credit: ").Append(Credit).Append("\n");
            sb.Append("  HasInstruction: ").Append(HasInstruction).Append("\n");
            sb.Append("  HasQuestionOptions: ").Append(HasQuestionOptions).Append("\n");
            sb.Append("  IdApp: ").Append(IdApp).Append("\n");
            sb.Append("  IdAppProject: ").Append(IdAppProject).Append("\n");
            sb.Append("  IdQuality: ").Append(IdQuality).Append("\n");
            sb.Append("  Instruction: ").Append(Instruction).Append("\n");
            sb.Append("  NbTaskClosed: ").Append(NbTaskClosed).Append("\n");
            sb.Append("  NbTotalTask: ").Append(NbTotalTask).Append("\n");
            sb.Append("  Qualities: ").Append(Qualities).Append("\n");
            sb.Append("  QualityName: ").Append(QualityName).Append("\n");
            sb.Append("  QuestionOptions: ").Append(QuestionOptions).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  TitleQuestionOptions: ").Append(TitleQuestionOptions).Append("\n");
            sb.Append("  UrlNotification: ").Append(UrlNotification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AppProjectReaderServiceModel);
        }

        /// <summary>
        /// Returns true if AppProjectReaderServiceModel instances are equal
        /// </summary>
        /// <param name="other">Instance of AppProjectReaderServiceModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AppProjectReaderServiceModel other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AppName == other.AppName ||
                    this.AppName != null &&
                    this.AppName.Equals(other.AppName)
                ) && 
                (
                    this.AppProjectState == other.AppProjectState ||
                    this.AppProjectState != null &&
                    this.AppProjectState.Equals(other.AppProjectState)
                ) && 
                (
                    this.CreationDate == other.CreationDate ||
                    this.CreationDate != null &&
                    this.CreationDate.Equals(other.CreationDate)
                ) && 
                (
                    this.Credit == other.Credit ||
                    this.Credit != null &&
                    this.Credit.Equals(other.Credit)
                ) && 
                (
                    this.HasInstruction == other.HasInstruction ||
                    this.HasInstruction != null &&
                    this.HasInstruction.Equals(other.HasInstruction)
                ) && 
                (
                    this.HasQuestionOptions == other.HasQuestionOptions ||
                    this.HasQuestionOptions != null &&
                    this.HasQuestionOptions.Equals(other.HasQuestionOptions)
                ) && 
                (
                    this.IdApp == other.IdApp ||
                    this.IdApp != null &&
                    this.IdApp.Equals(other.IdApp)
                ) && 
                (
                    this.IdAppProject == other.IdAppProject ||
                    this.IdAppProject != null &&
                    this.IdAppProject.Equals(other.IdAppProject)
                ) && 
                (
                    this.IdQuality == other.IdQuality ||
                    this.IdQuality != null &&
                    this.IdQuality.Equals(other.IdQuality)
                ) && 
                (
                    this.Instruction == other.Instruction ||
                    this.Instruction != null &&
                    this.Instruction.Equals(other.Instruction)
                ) && 
                (
                    this.NbTaskClosed == other.NbTaskClosed ||
                    this.NbTaskClosed != null &&
                    this.NbTaskClosed.Equals(other.NbTaskClosed)
                ) && 
                (
                    this.NbTotalTask == other.NbTotalTask ||
                    this.NbTotalTask != null &&
                    this.NbTotalTask.Equals(other.NbTotalTask)
                ) && 
                (
                    this.Qualities == other.Qualities ||
                    this.Qualities != null &&
                    this.Qualities.SequenceEqual(other.Qualities)
                ) && 
                (
                    this.QualityName == other.QualityName ||
                    this.QualityName != null &&
                    this.QualityName.Equals(other.QualityName)
                ) && 
                (
                    this.QuestionOptions == other.QuestionOptions ||
                    this.QuestionOptions != null &&
                    this.QuestionOptions.SequenceEqual(other.QuestionOptions)
                ) && 
                (
                    this.Title == other.Title ||
                    this.Title != null &&
                    this.Title.Equals(other.Title)
                ) && 
                (
                    this.TitleQuestionOptions == other.TitleQuestionOptions ||
                    this.TitleQuestionOptions != null &&
                    this.TitleQuestionOptions.Equals(other.TitleQuestionOptions)
                ) && 
                (
                    this.UrlNotification == other.UrlNotification ||
                    this.UrlNotification != null &&
                    this.UrlNotification.Equals(other.UrlNotification)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AppName != null)
                    hash = hash * 59 + this.AppName.GetHashCode();
                if (this.AppProjectState != null)
                    hash = hash * 59 + this.AppProjectState.GetHashCode();
                if (this.CreationDate != null)
                    hash = hash * 59 + this.CreationDate.GetHashCode();
                if (this.Credit != null)
                    hash = hash * 59 + this.Credit.GetHashCode();
                if (this.HasInstruction != null)
                    hash = hash * 59 + this.HasInstruction.GetHashCode();
                if (this.HasQuestionOptions != null)
                    hash = hash * 59 + this.HasQuestionOptions.GetHashCode();
                if (this.IdApp != null)
                    hash = hash * 59 + this.IdApp.GetHashCode();
                if (this.IdAppProject != null)
                    hash = hash * 59 + this.IdAppProject.GetHashCode();
                if (this.IdQuality != null)
                    hash = hash * 59 + this.IdQuality.GetHashCode();
                if (this.Instruction != null)
                    hash = hash * 59 + this.Instruction.GetHashCode();
                if (this.NbTaskClosed != null)
                    hash = hash * 59 + this.NbTaskClosed.GetHashCode();
                if (this.NbTotalTask != null)
                    hash = hash * 59 + this.NbTotalTask.GetHashCode();
                if (this.Qualities != null)
                    hash = hash * 59 + this.Qualities.GetHashCode();
                if (this.QualityName != null)
                    hash = hash * 59 + this.QualityName.GetHashCode();
                if (this.QuestionOptions != null)
                    hash = hash * 59 + this.QuestionOptions.GetHashCode();
                if (this.Title != null)
                    hash = hash * 59 + this.Title.GetHashCode();
                if (this.TitleQuestionOptions != null)
                    hash = hash * 59 + this.TitleQuestionOptions.GetHashCode();
                if (this.UrlNotification != null)
                    hash = hash * 59 + this.UrlNotification.GetHashCode();
                return hash;
            }
        }
    }

}
