/* 
 * Wirk
 *
 * API for api.wirk.io
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Wirk.Api.Wirk.Api;
using Io.Wirk.Api.Wirk.Model;
using Io.Wirk.Api.Wirk.Client;
using System.Reflection;

namespace Io.Wirk.Api.Wirk.Test
{
    /// <summary>
    ///  Class for testing AppProjectReaderServiceModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppProjectReaderServiceModelTests
    {
        private AppProjectReaderServiceModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AppProjectReaderServiceModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppProjectReaderServiceModel
        /// </summary>
        [Test]
        public void AppProjectReaderServiceModelInstanceTest()
        {
            Assert.IsInstanceOf<AppProjectReaderServiceModel> (instance, "instance is a AppProjectReaderServiceModel");
        }

        /// <summary>
        /// Test the property 'AppName'
        /// </summary>
        [Test]
        public void AppNameTest()
        {
            // TODO: unit test for the property 'AppName'
        }
        /// <summary>
        /// Test the property 'AppProjectState'
        /// </summary>
        [Test]
        public void AppProjectStateTest()
        {
            // TODO: unit test for the property 'AppProjectState'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO: unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'Credit'
        /// </summary>
        [Test]
        public void CreditTest()
        {
            // TODO: unit test for the property 'Credit'
        }
        /// <summary>
        /// Test the property 'HasInstruction'
        /// </summary>
        [Test]
        public void HasInstructionTest()
        {
            // TODO: unit test for the property 'HasInstruction'
        }
        /// <summary>
        /// Test the property 'HasQuestionOptions'
        /// </summary>
        [Test]
        public void HasQuestionOptionsTest()
        {
            // TODO: unit test for the property 'HasQuestionOptions'
        }
        /// <summary>
        /// Test the property 'IdApp'
        /// </summary>
        [Test]
        public void IdAppTest()
        {
            // TODO: unit test for the property 'IdApp'
        }
        /// <summary>
        /// Test the property 'IdAppProject'
        /// </summary>
        [Test]
        public void IdAppProjectTest()
        {
            // TODO: unit test for the property 'IdAppProject'
        }
        /// <summary>
        /// Test the property 'IdQuality'
        /// </summary>
        [Test]
        public void IdQualityTest()
        {
            // TODO: unit test for the property 'IdQuality'
        }
        /// <summary>
        /// Test the property 'Instruction'
        /// </summary>
        [Test]
        public void InstructionTest()
        {
            // TODO: unit test for the property 'Instruction'
        }
        /// <summary>
        /// Test the property 'NbTaskClosed'
        /// </summary>
        [Test]
        public void NbTaskClosedTest()
        {
            // TODO: unit test for the property 'NbTaskClosed'
        }
        /// <summary>
        /// Test the property 'NbTotalTask'
        /// </summary>
        [Test]
        public void NbTotalTaskTest()
        {
            // TODO: unit test for the property 'NbTotalTask'
        }
        /// <summary>
        /// Test the property 'Qualities'
        /// </summary>
        [Test]
        public void QualitiesTest()
        {
            // TODO: unit test for the property 'Qualities'
        }
        /// <summary>
        /// Test the property 'QualityName'
        /// </summary>
        [Test]
        public void QualityNameTest()
        {
            // TODO: unit test for the property 'QualityName'
        }
        /// <summary>
        /// Test the property 'QuestionOptions'
        /// </summary>
        [Test]
        public void QuestionOptionsTest()
        {
            // TODO: unit test for the property 'QuestionOptions'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO: unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'TitleQuestionOptions'
        /// </summary>
        [Test]
        public void TitleQuestionOptionsTest()
        {
            // TODO: unit test for the property 'TitleQuestionOptions'
        }
        /// <summary>
        /// Test the property 'UrlNotification'
        /// </summary>
        [Test]
        public void UrlNotificationTest()
        {
            // TODO: unit test for the property 'UrlNotification'
        }

    }

}
