/* 
 * Wirk
 *
 * <p>API for api.wirk.io</p> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@wirk.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Wirk.Api.Wirk.Api;
using Io.Wirk.Api.Wirk.Model;
using Io.Wirk.Api.Wirk.Client;
using System.Reflection;

namespace Io.Wirk.Api.Wirk.Test
{
    /// <summary>
    ///  Class for testing TaskLineReaderServiceModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskLineReaderServiceModelTests
    {
        private TaskLineReaderServiceModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TaskLineReaderServiceModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskLineReaderServiceModel
        /// </summary>
        [Test]
        public void TaskLineReaderServiceModelInstanceTest()
        {
            Assert.IsInstanceOf<TaskLineReaderServiceModel> (instance, "instance is a TaskLineReaderServiceModel");
        }

        /// <summary>
        /// Test the property 'IdAppProject'
        /// </summary>
        [Test]
        public void IdAppProjectTest()
        {
            // TODO: unit test for the property 'IdAppProject'
        }
        /// <summary>
        /// Test the property 'IdTaskLine'
        /// </summary>
        [Test]
        public void IdTaskLineTest()
        {
            // TODO: unit test for the property 'IdTaskLine'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO: unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Test]
        public void TasksTest()
        {
            // TODO: unit test for the property 'Tasks'
        }

    }

}
