/* 
 * Wirk
 *
 * API for api.wirk.io
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Io.Wirk.Api.Wirk.Client;
using Io.Wirk.Api.Wirk.Api;
using Io.Wirk.Api.Wirk.Model;

namespace Io.Wirk.Api.Wirk.Test
{
    /// <summary>
    ///  Class for testing AppApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AppApiTests
    {
        private AppApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AppApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf<AppApi> (instance, "instance is a AppApi");
        }

        
        /// <summary>
        /// Test Get
        /// </summary>
        [Test]
        public void GetTest()
        {
            // TODO: add unit test for the method 'Get'
            int? id = null; // TODO: replace null with proper value
            var response = instance.Get(id);
            Assert.IsInstanceOf<AppReaderServiceModel> (response, "response is AppReaderServiceModel");
        }
        
        /// <summary>
        /// Test GetAll
        /// </summary>
        [Test]
        public void GetAllTest()
        {
            // TODO: add unit test for the method 'GetAll'
            var response = instance.GetAll();
            Assert.IsInstanceOf<List<AppReaderServiceModel>> (response, "response is List<AppReaderServiceModel>");
        }
        
    }

}
